# Generated by Django 4.2.6 on 2023-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_infouser_options_alter_infouser_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('age', models.CharField(max_length=255, verbose_name='возраст')),
                ('nation', models.CharField(max_length=255, verbose_name='нация')),
                ('addres', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='телефон номер')),
                ('email', models.CharField(max_length=255, verbose_name='почта')),
                ('telegram', models.CharField(max_length=255, verbose_name='username телеграм')),
                ('language', models.CharField(max_length=255, verbose_name='знание языка')),
            ],
        ),
    ]
