# Generated by Django 4.2.6 on 2023-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'обо мне', 'verbose_name_plural': 'обо мне'},
        ),
        migrations.AddField(
            model_name='about',
            name='awards',
            field=models.CharField(default=1, max_length=255, verbose_name='полученные награды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='clients',
            field=models.CharField(default=1, max_length=255, verbose_name='счастливые клиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='project',
            field=models.CharField(default=1, max_length=255, verbose_name='завершенные проекты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='year',
            field=models.CharField(default=1, max_length=255, verbose_name='годы опыта'),
            preserve_default=False,
        ),
    ]
