# Generated by Django 4.2.6 on 2023-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_about_options_about_awards_about_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skiils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('number', models.CharField(max_length=255, verbose_name='процент')),
            ],
            options={
                'verbose_name': 'мой скил',
            },
        ),
    ]
