# Generated by Django 4.2.6 on 2023-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_skiils'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.CharField(max_length=255, verbose_name='почта')),
                ('message', models.CharField(max_length=255, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
