# Generated by Django 4.2.6 on 2023-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='place_of_work',
            field=models.CharField(default=1, max_length=255, verbose_name='место работы'),
            preserve_default=False,
        ),
    ]
