# Generated by Django 4.2.6 on 2023-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_experience_place_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description2',
            field=models.CharField(default=1, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='place_of_work2',
            field=models.CharField(default=1, max_length=255, verbose_name='место работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='profession2',
            field=models.CharField(default=1, max_length=255, verbose_name='профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='year2',
            field=models.CharField(default=11, max_length=255, verbose_name='год'),
            preserve_default=False,
        ),
    ]
