# Generated by Django 4.2.6 on 2023-11-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_experience_description2_experience_place_of_work2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place_of_work2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='место работы'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profession2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='год'),
        ),
    ]
