# Generated by Django 4.2.6 on 2023-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/', verbose_name='фото'),
        ),
    ]
