# Generated by Django 4.2.6 on 2023-11-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'портфолио', 'verbose_name_plural': 'портфолии'},
        ),
    ]
