# Generated by Django 4.2.6 on 2023-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_portfolio_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='clients',
            field=models.CharField(default=1, max_length=255, verbose_name='клиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='preview',
            field=models.CharField(default=1, max_length=255, verbose_name='предварительный просмотр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.CharField(default=1, max_length=255, verbose_name='проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_name',
            field=models.CharField(default=1, max_length=255, verbose_name='название проекта'),
            preserve_default=False,
        ),
    ]
